{{- if .Values.autoscaler.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-api
  labels:
{{ include "labels" . | indent 6 }}

spec:
  minReplicas: 1
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.averageCPU }}
    - type: Object
      object:
        metric:
          name: envoy_upstream_active_requests
        describedObject:
          apiVersion: custom.metrics.k8s.io/v1beta1
          kind: MetricValueList
          name: envoy_upstream_active_requests
        target:
          averageValue: "100"
{{- end }}
