api:
    db:
        user: ENC[AES256_GCM,data:13vUWn/DSZNdNSjx,iv:5gG6tB417tERnY2Y8xnGXGhzSDetXBjGIPGPvETzhpE=,tag:CHJgYos+72tO/HJ5O13vsg==,type:str]
        password: ENC[AES256_GCM,data:uVvAFMrfQ3aFT4CLorBsXI4+07Xav9Y+r3GmmyTzgb9a9pNCtsq4IYiUDqIjFIwsl8xuha6g8tqVJbTUTg76rg==,iv:Rlcgj4pk3PMcULpL3UPo0Add0uIzqw539HgijeWRy/o=,tag:sNxt/cNw4hQZsBtEF8byPQ==,type:str]
        host: ENC[AES256_GCM,data:jqzWt+BzQX4o0HYgXfuw5uHXguoVaEhc5eT2qCfhlamFw7YMrmYgCAY=,iv:H/1qS1rzLBr6PVtfF1p7Q13b2jRwU10Empv6vZCbhaQ=,tag:cVpRL0pI3F33vw4C15Yeww==,type:str]
worker:
    db:
        user: ENC[AES256_GCM,data:rl2S6a57apcIb1hh,iv:c3zNePKRQZxDNteq++92TKvwrVdjNxEGgRUS5C8ARwk=,tag:8Cu6GZwQepeGPCUx2J21Gg==,type:str]
        password: ENC[AES256_GCM,data:pAZtgVA48D13JwC3OaZ9gwjGxH8vnMUi1C0NhLekqOEJ3/UOSQeLsr76WtzA5sCSn/QEhrvcG9crfcb1H5qNhQ==,iv:OIYAdsU1XbIiwZ6Zp/Vo7llrcbwrktjKcHe+0oPay4s=,tag:/v83oSm0dg5JHmgc5newIQ==,type:str]
        host: ENC[AES256_GCM,data:wXgps+hr2n9ipnlGg/YPAnZKZ+cE2vkXaNsbXL3fJ88KpIHg,iv:osaAKi4PrSKE+g/SPaJ85vtfcEegrXIn2jotEJHlAmo=,tag:tioFJLXUN33WG8h/w2XXbw==,type:str]
kafka:
    kafkaBrokerURL: ENC[AES256_GCM,data:zD0W17NwfEtoevtFR6k9eeTk2i3Du7pw4C9y0XVb45AjfQpEZS2U9ot8UQ+I+SkZYDpJUtkITkU=,iv:79Tj5lMuoXD93QCjcrLcE/HDGmx/n/xywBB8M3vUTv0=,tag:DLGAfX9nxj4FQZTydyc92Q==,type:str]
    schemaRegistryURL: ENC[AES256_GCM,data:fFaxtE6FrsNZb7BHHICFDWhWc/rGuOSj37pxH1uR9EHSVLH8ARki8XGPNqqByMPu4p31CAQKsVy1UalerQ==,iv:6JvZE4Lm3zxkgohDOIyx3IG+RhZqL/o3C8/ttNepw1o=,tag:MXrrBml7BkbjrJfHdw75xQ==,type:str]
db:
    name: ENC[AES256_GCM,data:SJIcd1Mq,iv:uvW6EmNTQqiVSbWbptOw1k/0qVV9GAaoygyHUr7L88s=,tag:5FMrhgr9NY1634AHIioofQ==,type:str]
#ENC[AES256_GCM,data:RU4BsPFk,iv:ezHelBdL5EROlu7zvd27lUn5cLMWrgVqoqd5SN5yf7k=,tag:TzHj/qJ8QvD/RM02hCdv1A==,type:comment]
#ENC[AES256_GCM,data:4DRItv8qslFuc0XGM7LRlcLZjjmF21cpnn4zaU3IzTU=,iv:8p0ofKbPp7q+8Lmewm/V5kSCkyDQDyP++XZOaDtq9x4=,tag:eIrQIgkuo2iH9Y6hq/OjaQ==,type:comment]
#ENC[AES256_GCM,data:4B9w+9LplVrTLrk=,iv:/ldkEAbZvvgWvwz26fQD3IJQQYmnZpjI6Z3gAxTty1A=,tag:reCybf+PaNQCD9nBVkIryQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://vault.geometry-dev.net:8200
          engine_path: sops
          key_name: dev-us-west-2
          created_at: "2021-08-23T20:30:55Z"
          enc: vault:v1:E2xzv4Vvt/NiUZmX6POC4knAPCSrd6TedEyJqpelnXpKjRzNOGBIBMrBfdOKLnLbuwNF/d/oVeEtYjZRiGlqa+ytimcxAHa8ylpnsjtPSIEEYZ/U81A1702YiiavxwuREfmEQA5k93L0LSGKU5STkkobjBKMR81RVF5PjwXAURId+u+xtpjP7Nj9qg4XrJFMQGwyuBLuSkceOlcznGTl0sp2LjcI57Td+gkBACXg8qK9XaOkAmqbU1AAnHFQHmv/OL5LQ4bRsn+6XBKeRByqjVzBHuywqXTBmgNr8uDBZ++bHOdaFOZluPxgdtnkugugjl3F5xT2wyFSgcXQU/iFoCNMWqZWJI/zaCxhuSn4kuqs5dC2IfvpAeRanWArQQI2eCWfDWNdlC5mhnHOZoS+BB1SM7HHgki+QNR+UjhFHyjf8KVmzflR8S7AiGlpc9UdskSjPoipP0cUZhf+iRyOYJAFU4qiYADE5/2H30bjFb2MTCgPgyV9DOnaNv17BvSTX6ke3npZGhcKAp63ky7+eXA4Olbg7kaNq8qOtzFVze+yIoAbXytB/TxqdBf8AQxTOjNK1ZLQmcjwCug89fXYtFBChnvMSjjV5l0emEbD5tl0/6Xv8lhjAfZc4XypVTnwYFjSKYTnvoR/4fvNHXpbtvsbsiMpLkAuNAOdZoPzwXM=
    age: []
    lastmodified: "2021-10-08T18:14:29Z"
    mac: ENC[AES256_GCM,data:DW8SfCMHuettigl3A4gTkJvWO0dr23nujXQhBRNbDwyBldwpzI3c1fUoNSGZ25X+792tu9A47wcVJMTY8yeegZrR6gemCGEj3CSFTyokAXI2am0LQZDzp+RMPCliNj9H/I6CYvLhqnzKoRGbswjchyTQRJz4NqGb8s0MfEEKLSg=,iv:HZgS4uJOfY78N6zKgZzgZbskx4DqFO+R+QhG42JmbqQ=,tag:9oK3NYOCed+KRV4B9AKyqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
