name: PR run tests

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Bring up DBs
        run: docker-compose -f docker-compose.db.yml up -d

      - name: Run unit tests
        run: cd src && go test ./... -v

      - name: Bring up stack
        run: make up

      - name: Run integration tests
        run: sleep 120 && cd tests && go test ./... -v
